apiVersion: apps/v1
kind: Deployment
metadata:
  name: "fargate-service-deployment"
  # This namespace needs to be created in Terraform as service account will also be in this namespace.
  namespace: {{ quote .Values.chartNameSpace }}
  labels:
    app: "fargate-service-1" # This the label for the deployment itself and not the pod.
spec:
  replicas: 1
  selector:
    matchLabels:
      # This is to maintain replicas. Selecting pod template labels here.
      app: "fargate-service-1"
  template:
    # This is the metadata for the pod and not for the deployment.
    metadata:
      name: "fargate-service-1"
      namespace: {{ quote .Values.chartNameSpace }}
      labels:
        app: "fargate-service-1"
        chart: {{ quote .Chart.Name }}
        release: {{ quote .Release.Name }}
        version:
      annotations:
        "kubernetes.io/managed-by": "helm"
    spec:
      containers:
        - name: {{ quote .Values.image.repository }}
          image: {{ quote .Values.image.imageVersion }}
          imagePullPolicy: {{ quote .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "0.25"
              memory: "256M"
            limits:
              cpu: "0.25"
              memory: "256M"
      restartPolicy: Always
      serviceAccountName: "cluster-fargate-s3-sa"

