apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "fargate-service-1-as"
  namespace: {{ quote .Values.chartNameSpace }}
  labels:
    app: "fargate-service-1"
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "fargate-service-deployment"
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
