apiVersion: v1
kind: Service
metadata:
  name: "fargate-service-1-service"
  namespace: {{ quote .Values.chartNameSpace }}
  labels:
    app: "fargate-service-1"
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: "fargate-service-1"
  ports:
    - port: 80
      targetPort: 80 # Port on the pod that the request must be forwarded
      protocol: TCP
  type: ClusterIP
