replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  imageVersion: "nginx:1.14.2"


chartNameSpace: "fargate-cluster"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Use double-quoted strings when possible we can escape characters in them using a /.
service:
  type: ClusterIP
  port: 80
  name: "fargate-service-1"

ingress:
  name: "fargate-ingress"
  className: "alb"

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80