# This example attaches the service account to AWS IAM role. Instead of AWS IAM based permissions
# we can also attach K8s Cluster Role or Role using a Role binding.
# Note to attach AWS IAM roles we don't need binding like RoleBinding or ClusterRoleBinding.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-access-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<role-name>